name = "gcm-business-intelligence-worker"
main = "worker.js"
compatibility_date = "2026-07-02"

[vars]
ENVIRONMENT = "development"

[ai]
binding = "AI"

[images]
binding = "IMAGES"

[[d1_databases]]
binding = "DB"
database_name = "gcm-operating-system"
database_id = "ce93408a-85ee-4103-88aa-cd4a12169305"
