-- =========================================================
-- Global Concepts Media Operating System
-- File: migrations/0027_schedule_operations.sql
-- Version: 1.0.0
-- Status: Production Migration Candidate
-- Purpose: Durable campaign/event schedule authority with human-reviewed
--          change candidates, version history, and one-source multi-calendar reads.
-- =========================================================
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schedule_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER,
  source_key TEXT NOT NULL UNIQUE,
  item_type TEXT NOT NULL,
  title TEXT NOT NULL,
  market TEXT,
  channel TEXT,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  start_time TEXT,
  status TEXT NOT NULL DEFAULT 'planned',
  source_reference TEXT,
  notes TEXT,
  metadata_json TEXT,
  version_number INTEGER NOT NULL DEFAULT 1,
  created_by TEXT NOT NULL DEFAULT 'Andy',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at TEXT,
  FOREIGN KEY (client_id) REFERENCES clients(id)
);
CREATE INDEX IF NOT EXISTS idx_schedule_items_dates ON schedule_items(start_date,end_date,status);
CREATE INDEX IF NOT EXISTS idx_schedule_items_client ON schedule_items(client_id,item_type,start_date);

CREATE TABLE IF NOT EXISTS schedule_change_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER,
  request_type TEXT NOT NULL,
  target_item_id INTEGER,
  title TEXT NOT NULL,
  proposed_json TEXT NOT NULL,
  reason TEXT,
  source_reference TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  requested_by TEXT NOT NULL DEFAULT 'Andy',
  reviewed_by TEXT,
  reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES clients(id),
  FOREIGN KEY (target_item_id) REFERENCES schedule_items(id)
);
CREATE INDEX IF NOT EXISTS idx_schedule_change_requests_status ON schedule_change_requests(status,created_at DESC);

CREATE TABLE IF NOT EXISTS schedule_item_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  schedule_item_id INTEGER NOT NULL,
  change_request_id INTEGER,
  version_number INTEGER NOT NULL,
  snapshot_json TEXT NOT NULL,
  change_type TEXT NOT NULL,
  changed_by TEXT NOT NULL DEFAULT 'Andy',
  changed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (schedule_item_id) REFERENCES schedule_items(id),
  FOREIGN KEY (change_request_id) REFERENCES schedule_change_requests(id)
);
CREATE INDEX IF NOT EXISTS idx_schedule_item_history_item ON schedule_item_history(schedule_item_id,version_number DESC);

INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2026-10-03','gun_show','SES Melbourne Gun Show','Melbourne','Event','2026-10-03','2026-10-04','confirmed','https://sesafes.com/pages/shows','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"SES show schedule","participationStatus":"confirmed"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2026-10-10','gun_show','SES Orlando Gun Show','Orlando','Event','2026-10-10','2026-10-11','confirmed','https://sesafes.com/pages/shows','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"SES show schedule","participationStatus":"confirmed"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2026-11-28','gun_show','SES Melbourne Gun Show','Melbourne','Event','2026-11-28','2026-11-29','confirmed','https://sesafes.com/pages/shows','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"SES show schedule","participationStatus":"confirmed"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2026-11-28','gun_show','SES Orlando Gun Show','Orlando','Event','2026-11-28','2026-11-29','confirmed','https://sesafes.com/pages/shows','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"SES show schedule","participationStatus":"confirmed"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-01-02','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-01-02','2027-01-03','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2027-01-16','gun_show','SES Orlando Gun Show','Orlando','Event','2027-01-16','2027-01-17','candidate','https://www.floridagunshows.com/florida-gun-show-schedule/','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Florida Gun Shows official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-02-06','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-02-06','2027-02-07','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-03-06','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-03-06','2027-03-07','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2027-03-13','gun_show','SES Orlando Gun Show','Orlando','Event','2027-03-13','2027-03-14','candidate','https://www.floridagunshows.com/florida-gun-show-schedule/','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Florida Gun Shows official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-04-17','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-04-17','2027-04-18','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2027-05-15','gun_show','SES Orlando Gun Show','Orlando','Event','2027-05-15','2027-05-16','candidate','https://www.floridagunshows.com/florida-gun-show-schedule/','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Florida Gun Shows official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-05-22','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-05-22','2027-05-23','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-07-10','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-07-10','2027-07-11','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2027-07-10','gun_show','SES Orlando Gun Show','Orlando','Event','2027-07-10','2027-07-11','candidate','https://www.floridagunshows.com/florida-gun-show-schedule/','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Florida Gun Shows official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-08-21','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-08-21','2027-08-22','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2027-08-21','gun_show','SES Orlando Gun Show','Orlando','Event','2027-08-21','2027-08-22','candidate','https://www.floridagunshows.com/florida-gun-show-schedule/','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Florida Gun Shows official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-10-02','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-10-02','2027-10-03','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2027-10-09','gun_show','SES Orlando Gun Show','Orlando','Event','2027-10-09','2027-10-10','candidate','https://www.floridagunshows.com/florida-gun-show-schedule/','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Florida Gun Shows official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:melbourne:2027-11-27','gun_show','SES Melbourne Gun Show','Melbourne','Event','2027-11-27','2027-11-28','candidate','https://flgunshows.com/shows/','{"venue":"Melbourne Auditorium","station":"WMMB","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Sport Show Specialists official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:gun-show:orlando:2027-11-27','gun_show','SES Orlando Gun Show','Orlando','Event','2027-11-27','2027-11-28','candidate','https://www.floridagunshows.com/florida-gun-show-schedule/','{"venue":"Central Florida Fairgrounds","station":"WFLA","trafficWarningDaysBeforeFlightStart":7,"stationDeadlineDaysBeforeFlightStart":2,"stationDeadlineTime":"10:00","flightStartOffsetDays":-3,"flightEndOffsetDays":0,"alertRecipients":["Andy","Kristy"],"socialChannels":["Facebook","Google Business Profile","Instagram"],"socialSequence":[{"offset":-5,"title":"SOCIAL #1 — SHOW WEEK ANNOUNCEMENT","theme":"See you at the gun show this weekend"},{"offset":-4,"title":"SOCIAL #2 — WHY BUY AT THE SHOW","theme":"Compare sizes, lock options, ask questions, find the right fit"},{"offset":-3,"title":"SOCIAL #3 — SHOW SAVINGS","theme":"Special inventory, closeouts, and cash & carry opportunities"},{"offset":-2,"title":"SOCIAL #4 — PROTECT WHAT MATTERS","theme":"Protection for firearms, valuables, documents, and peace of mind"},{"offset":-1,"title":"SOCIAL #5 — STARTS TOMORROW","theme":"Come early for the best selection"},{"offset":0,"title":"SOCIAL #6 — WE''RE HERE TODAY","theme":"Stop by the Southeast Safes display"}],"sourceType":"Florida Gun Shows official schedule","participationStatus":"official_schedule_candidate"}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;

INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:liberty:fall-savings-2026','promotion','Liberty Fall Savings — BOGO','All SES','Liberty Safe','2026-10-15','2026-11-01','planned','UPCOMING PROMOS','{"offer":"Buy a qualifying safe and receive a free handgun vault. Vault tier depends on safe model.","schedule":[{"date":"2026-10-15","title":"SOCIAL — FALL SAVINGS LAUNCH","theme":"Launch the BOGO offer and explain the free handgun-vault benefit."},{"date":"2026-10-20","title":"SOCIAL — FALL SAVINGS PRODUCT FEATURE","theme":"Feature qualifying safe families and the included handgun-vault value."},{"date":"2026-10-25","title":"SOCIAL — FALL SAVINGS REMINDER","theme":"Mid-promotion reminder focused on protection + added value."},{"date":"2026-10-31","title":"SOCIAL — FALL SAVINGS FINAL WEEKEND","theme":"Final-weekend urgency; promotion ends tomorrow."},{"date":"2026-11-01","title":"SOCIAL — FALL SAVINGS FINAL DAY","theme":"Final-day call to action."}],"channels":["Facebook","Google Business Profile","Instagram"],"embargoUntil":null,"source":{"gmailMessageId":"1a1021fa34f00798","subject":"UPCOMING PROMOS","attachment":"Fall Savings, Veterans Day, Blk Friday-Cyber Mon..docx","forwardedDealerNewsMessageId":"1a1022169a8d3a11"}}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:liberty:home-advantage-launch-2026','promotion','Liberty Home Advantage Launch','All SES','Liberty Safe','2026-10-28','2026-10-28','planned','UPCOMING PROMOS','{"offer":"Consumer launch. Do not publish any Home Advantage content before October 28.","schedule":[{"date":"2026-10-28","title":"SOCIAL — HOME ADVANTAGE LAUNCH","theme":"Launch-day post only; embargo lifts October 28."}],"channels":["Facebook","Google Business Profile","Instagram"],"embargoUntil":"2026-10-28","source":{"gmailMessageId":"1a1021fa34f00798","subject":"UPCOMING PROMOS","attachment":"Fall Savings, Veterans Day, Blk Friday-Cyber Mon..docx","forwardedDealerNewsMessageId":"1a1022169a8d3a11"}}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:liberty:veterans-day-2026','promotion','Liberty Veterans Day Sale','All SES','Liberty Safe','2026-11-05','2026-11-11','planned','UPCOMING PROMOS','{"offer":"250th Commemorative safes with special pricing; USA 30 OD Green with Gold Logo/Hardware is $175 off.","schedule":[{"date":"2026-11-05","title":"SOCIAL — VETERANS DAY SALE LAUNCH","theme":"Open the Veterans Day promotion and highlight commemorative safes."},{"date":"2026-11-08","title":"SOCIAL — VETERANS DAY FEATURE","theme":"Feature USA 30 OD Green and/or 250th Commemorative models."},{"date":"2026-11-10","title":"SOCIAL — VETERANS DAY ENDS TOMORROW","theme":"24-hour urgency reminder."},{"date":"2026-11-11","title":"SOCIAL — VETERANS DAY FINAL DAY","theme":"Final-day Veterans Day promotion post."}],"channels":["Facebook","Google Business Profile","Instagram"],"embargoUntil":null,"source":{"gmailMessageId":"1a1021fa34f00798","subject":"UPCOMING PROMOS","attachment":"Fall Savings, Veterans Day, Blk Friday-Cyber Mon..docx","forwardedDealerNewsMessageId":"1a1022169a8d3a11"}}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:liberty:pre-black-friday-2026','promotion','Liberty Pre-Black Friday Sale','All SES','Liberty Safe','2026-11-12','2026-11-30','planned','UPCOMING PROMOS','{"offer":"Select Home, Home SE and Colonial models discounted $100–$500.","schedule":[{"date":"2026-11-12","title":"SOCIAL — PRE-BLACK FRIDAY LAUNCH","theme":"Launch sale with select Home and Colonial savings."},{"date":"2026-11-17","title":"SOCIAL — PRE-BLACK FRIDAY HOME SAFE FEATURE","theme":"Feature Home Safe 8/12 and Home SE savings."},{"date":"2026-11-22","title":"SOCIAL — PRE-BLACK FRIDAY COLONIAL FEATURE","theme":"Feature Colonial 23/30/50 savings."},{"date":"2026-11-25","title":"SOCIAL — PRE-BLACK FRIDAY REMINDER","theme":"Thanksgiving-week reminder before Black Friday weekend."}],"channels":["Facebook","Google Business Profile","Instagram"],"embargoUntil":null,"source":{"gmailMessageId":"1a1021fa34f00798","subject":"UPCOMING PROMOS","attachment":"Fall Savings, Veterans Day, Blk Friday-Cyber Mon..docx","forwardedDealerNewsMessageId":"1a1022169a8d3a11"}}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:liberty:black-friday-2026','promotion','Liberty Black Friday Sale','All SES','Liberty Safe','2026-11-27','2026-11-30','planned','UPCOMING PROMOS','{"offer":"USA 50, USA 48 and Centurion 24 Black Friday specials; listed savings up to $491.","schedule":[{"date":"2026-11-27","title":"SOCIAL — BLACK FRIDAY","theme":"Black Friday launch; highlight featured USA and Centurion models."},{"date":"2026-11-28","title":"SOCIAL — BLACK FRIDAY + GUN SHOW","theme":"Combine Black Friday offer with the scheduled gun-show post rather than duplicate messaging."},{"date":"2026-11-29","title":"SOCIAL — BLACK FRIDAY FINAL WEEKEND","theme":"Final-weekend reminder."}],"channels":["Facebook","Google Business Profile","Instagram"],"embargoUntil":null,"source":{"gmailMessageId":"1a1021fa34f00798","subject":"UPCOMING PROMOS","attachment":"Fall Savings, Veterans Day, Blk Friday-Cyber Mon..docx","forwardedDealerNewsMessageId":"1a1022169a8d3a11"}}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;
INSERT OR IGNORE INTO schedule_items (client_id,source_key,item_type,title,market,channel,start_date,end_date,status,source_reference,metadata_json,created_by)
SELECT id,'ses:liberty:cyber-monday-2026','promotion','Liberty Cyber Monday','All SES','Liberty Safe','2026-11-30','2026-11-30','planned','UPCOMING PROMOS','{"offer":"Centurion 24 Black Texture with black chrome Spartan electronic lock — $699 sale price, $130 savings.","schedule":[{"date":"2026-11-30","title":"SOCIAL — CYBER MONDAY / FINAL DAY","theme":"Cyber Monday feature plus final-day close for the Pre-Black Friday and Black Friday promotional period."}],"channels":["Facebook","Google Business Profile","Instagram"],"embargoUntil":null,"source":{"gmailMessageId":"1a1021fa34f00798","subject":"UPCOMING PROMOS","attachment":"Fall Savings, Veterans Day, Blk Friday-Cyber Mon..docx","forwardedDealerNewsMessageId":"1a1022169a8d3a11"}}','Andy' FROM clients WHERE LOWER(client_code)='ses' LIMIT 1;

INSERT OR IGNORE INTO schedule_item_history (schedule_item_id,version_number,snapshot_json,change_type,changed_by)
SELECT id,version_number,json_object(
 'sourceKey',source_key,'itemType',item_type,'title',title,'market',market,'channel',channel,
 'startDate',start_date,'endDate',end_date,'startTime',start_time,'status',status,
 'sourceReference',source_reference,'notes',notes,'metadataJson',metadata_json
),'seed','System' FROM schedule_items WHERE source_key LIKE 'ses:%';
